server:
  port: 8888


# 必须有，以下配置文件，knife4j插件自动获取
knife4j:
  enable: true
  production: false
  # 接口文档是否需要密码
  basic:
    enable: false
    username: username
    password: password
  setting:
    # 默认语言
    language: zh-CN
    # 是否显示Footer
    enableFooter: false
    # 是否开启动态参数调试功能
    enableDynamicParameter: true
    # 是否在每个Debug调试栏后显示刷新变量按钮
    enableReloadCacheParameter: true

# 以下配置文件，自定义properties获取
swagger:
  enable: true
  title: "二手图书售卖系统后台"
  description: "二手图书售卖系统后台的api接口文档"
  version: "1.0.0"
  pathMapping: /api
  # 作者信息
  contact:
    name: "wang"
    email: "xxxx@qq.com"
    url: "https://xxxx.com"
  # 接口文档分组
  groups:
    - name: 1.接口文档一
      basePackage: com.xxxx.controller.apiA
    - name: 2.接口文档二
      basePackage: com.xxxx.controller.apiB