server:
  port: 8888

spring:
  mvc:
    pathmatch:
      # 适配 boot 2.6 路由与 springfox 兼容
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql8:3306/wang_book?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true
    username: root
    password: 123456
  redis:
    port: 6379
    host: redis6
    password: 123456


# 必须有，以下配置文件，knife4j插件自动获取
knife4j:
  enable: true
  production: false
  # 接口文档是否需要密码
  basic:
    enable: false
    username: username
    password: password
  setting:
    # 默认语言
    language: zh-CN
    # 是否显示Footer
    enableFooter: false
    # 是否开启动态参数调试功能
    enableDynamicParameter: true
    # 是否在每个Debug调试栏后显示刷新变量按钮
    enableReloadCacheParameter: true

# 以下配置文件，自定义properties获取
swagger:
  enable: true
  title: "二手图书售卖系统后台"
  description: "二手图书售卖系统后台的api接口文档"
  version: "1.0.0"
  pathMapping: /
  # 作者信息
  contact:
    name: "wang"
    email: "xxxx@qq.com"
    url: "https://xxxx.com"
  # 接口文档分组
  groups:
    - name: 1.普通用户接口文档
      basePackage: com.wang.controller.user
    - name: 2.管理员接口文档
      basePackage: com.wang.controller.manage


mybatis-plus:
  # 实体类包路径，用于在xml中通过类名使用实体类
  type-aliases-package: com.wang.pojo
  # xml文件包路径
  mapper-locations: classpath*:mapper/**/*.xml
  # mapper接口路径
  mapper-packages: com.wang.mapper
  global-config:
    db-config:
      # 表名前缀
      table-prefix: tb_
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl


token:
  #  header中token的键
  key: token
  # token生成密钥
  salt: wangqingze
  # token过期时间/min
  expire: 30